version: 2.1
jobs:
  test:
    docker:
      - image: pbxx/go-docker-base
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    working_directory: /go/src/github.com/promoboxx/go-glitch
    steps:
      - checkout

      - run:
          name: go vet
          command: go vet -mod vendor ./fb/...
      - run:
          name: gofmt
          command: test -z "$(gofmt -s -l fb)"
      - run:
          name: go test
          command: go test -race -run Unit ./...

      - store_test_results:
          path: testresults
workflows:
  version: 2.1
  test:
    jobs:
      - test
